import type {
  Lead,
  Appointment,
  Conversation,
  KnowledgeItem,
  AIEmployee,
  Plan,
} from './types';

export const demoLeads: Lead[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    phone: '(555) 234-1102',
    email: 'sarah.mitchell@email.com',
    service: 'Emergency leak repair',
    source: 'AI Receptionist',
    status: 'new',
    value: 450,
    notes: 'Kitchen pipe leaking, needs same-day service. Lives in primary service area.',
    nextFollowUp: 'Today 2:00 PM',
    createdAt: '2026-08-08T09:14:00Z',
  },
  {
    id: '2',
    name: 'James Okafor',
    phone: '(555) 887-4421',
    email: 'j.okafor@email.com',
    service: 'AC installation quote',
    source: 'AI Sales Assistant',
    status: 'contacted',
    value: 3200,
    notes: 'Wants 3 quotes for full home AC replacement. Prefers email contact.',
    nextFollowUp: 'Today 4:30 PM',
    createdAt: '2026-08-07T14:22:00Z',
  },
  {
    id: '3',
    name: 'Linda Chen',
    phone: '(555) 119-6677',
    email: 'lindachen@email.com',
    service: 'Annual HVAC maintenance',
    source: 'Website chat',
    status: 'qualified',
    value: 280,
    notes: 'Recurring maintenance plan interest. Has two rental properties.',
    nextFollowUp: 'Tomorrow 10:00 AM',
    createdAt: '2026-08-07T11:05:00Z',
  },
  {
    id: '4',
    name: 'Robert Hayes',
    phone: '(555) 442-8890',
    email: 'r.hayes@email.com',
    service: 'Bathroom remodel plumbing',
    source: 'AI Receptionist',
    status: 'won',
    value: 1850,
    notes: 'Booked and deposit collected. Job scheduled for next week.',
    nextFollowUp: '',
    createdAt: '2026-08-05T16:40:00Z',
  },
  {
    id: '5',
    name: 'Maria Santos',
    phone: '(555) 663-2210',
    email: 'm.santos@email.com',
    service: 'Water heater replacement',
    source: 'Phone (missed)',
    status: 'new',
    value: 1200,
    notes: 'Called after hours, AI captured details. Wants call back today.',
    nextFollowUp: 'Today 1:00 PM',
    createdAt: '2026-08-08T07:45:00Z',
  },
  {
    id: '6',
    name: 'David Kim',
    phone: '(555) 778-3344',
    email: 'dkim@email.com',
    service: 'Electrical panel upgrade',
    source: 'AI Sales Assistant',
    status: 'contacted',
    value: 2400,
    notes: 'Older home, needs 200amp panel. Sent quote, awaiting decision.',
    nextFollowUp: 'Aug 9 9:00 AM',
    createdAt: '2026-08-06T13:15:00Z',
  },
  {
    id: '7',
    name: 'Patricia Walsh',
    phone: '(555) 225-7798',
    email: 'p.walsh@email.com',
    service: 'Roof inspection',
    source: 'Website chat',
    status: 'lost',
    value: 350,
    notes: 'Went with competitor. Price-sensitive customer.',
    nextFollowUp: '',
    createdAt: '2026-08-03T10:30:00Z',
  },
];

export const demoAppointments: Appointment[] = [
  {
    id: '1',
    customerName: 'Robert Hayes',
    phone: '(555) 442-8890',
    service: 'Bathroom remodel plumbing',
    date: 'Aug 12',
    time: '9:00 AM',
    status: 'confirmed',
    notes: 'Deposit collected. Customer confirmed via AI Appointment Assistant.',
  },
  {
    id: '2',
    customerName: 'Sarah Mitchell',
    phone: '(555) 234-1102',
    service: 'Emergency leak repair',
    date: 'Today',
    time: '2:30 PM',
    status: 'scheduled',
    notes: 'Same-day emergency call. AI Receptionist booked.',
  },
  {
    id: '3',
    customerName: 'Linda Chen',
    phone: '(555) 119-6677',
    service: 'HVAC maintenance - Rental 1',
    date: 'Aug 10',
    time: '10:00 AM',
    status: 'confirmed',
    notes: 'First of two rental properties.',
  },
  {
    id: '4',
    customerName: 'James Okafor',
    phone: '(555) 887-4421',
    service: 'AC installation site visit',
    date: 'Aug 9',
    time: '1:00 PM',
    status: 'scheduled',
    notes: 'Quote site visit. Customer will be home.',
  },
  {
    id: '5',
    customerName: 'Eddie Torres',
    phone: '(555) 990-1122',
    service: 'Furnace tune-up',
    date: 'Aug 7',
    time: '3:00 PM',
    status: 'completed',
    notes: 'Service completed. Review request sent automatically.',
  },
  {
    id: '6',
    customerName: 'Greg Nolan',
    phone: '(555) 334-8891',
    service: 'Drain cleaning',
    date: 'Aug 6',
    time: '11:00 AM',
    status: 'no-show',
    notes: 'Customer did not arrive. AI will follow up to reschedule.',
  },
];

export const demoConversations: Conversation[] = [
  {
    id: '1',
    customerName: 'Sarah Mitchell',
    channel: 'web',
    lastMessage: 'That works — 2:30 today is great, thank you!',
    time: '9:14 AM',
    status: 'active',
    leadStatus: 'new',
    appointment: { date: 'Today', time: '2:30 PM' },
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'Hi, I have a kitchen pipe that won\'t stop leaking. Can someone come today?',
        time: '9:08 AM',
      },
      {
        id: 'm2',
        sender: 'ai',
        text: 'I\'m sorry to hear about the leak! We do offer same-day emergency service in your area. I can have a technician out this afternoon. Would 2:30 PM work for you?',
        time: '9:09 AM',
      },
      {
        id: 'm3',
        sender: 'customer',
        text: 'Yes, 2:30 works. How much is the call-out fee?',
        time: '9:11 AM',
      },
      {
        id: 'm4',
        sender: 'ai',
        text: 'Our emergency call-out fee is $120, which is credited toward any repair work performed. The technician will provide a full quote before starting any work. Shall I book the 2:30 PM slot?',
        time: '9:12 AM',
      },
      {
        id: 'm5',
        sender: 'customer',
        text: 'That works — 2:30 today is great, thank you!',
        time: '9:14 AM',
      },
    ],
  },
  {
    id: '2',
    customerName: 'Maria Santos',
    channel: 'phone',
    lastMessage: 'AI captured: water heater replacement, callback requested.',
    time: '7:45 AM',
    status: 'awaiting-human',
    leadStatus: 'new',
    appointment: null,
    messages: [
      {
        id: 'm1',
        sender: 'ai',
        text: 'Thanks for calling Apex Plumbing & Heating. We\'re currently unavailable, but I can help. What do you need?',
        time: '7:44 AM',
      },
      {
        id: 'm2',
        sender: 'customer',
        text: 'My water heater is dead, I need a replacement. Can someone call me back?',
        time: '7:44 AM',
      },
      {
        id: 'm3',
        sender: 'ai',
        text: 'I\'ve captured that. A technician will call you back this morning. Is (555) 663-2210 the best number?',
        time: '7:45 AM',
      },
      {
        id: 'm4',
        sender: 'customer',
        text: 'Yes that\'s right. Please call before noon.',
        time: '7:45 AM',
      },
    ],
  },
  {
    id: '3',
    customerName: 'James Okafor',
    channel: 'web',
    lastMessage: 'Looking forward to the quote. Thanks.',
    time: 'Yesterday',
    status: 'resolved',
    leadStatus: 'contacted',
    appointment: { date: 'Aug 9', time: '1:00 PM' },
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        text: 'I need 3 quotes for a full AC replacement.',
        time: '2:18 PM',
      },
      {
        id: 'm2',
        sender: 'ai',
        text: 'I can arrange a free site visit so we can give you an accurate quote. Would August 9 at 1:00 PM work?',
        time: '2:20 PM',
      },
      {
        id: 'm3',
        sender: 'customer',
        text: 'Yes, that\'s fine.',
        time: '2:21 PM',
      },
      {
        id: 'm4',
        sender: 'ai',
        text: 'Booked. The technician will arrive August 9 at 1:00 PM. You\'ll get a reminder the day before. Looking forward to the quote. Thanks.',
        time: '2:22 PM',
      },
    ],
  },
];

export const demoKnowledge: KnowledgeItem[] = [
  {
    id: '1',
    category: 'service',
    title: 'Emergency Plumbing Repair',
    content: '24/7 emergency plumbing for leaks, bursts, and backups. Same-day response in primary service area. Call-out fee $120, credited toward repair.',
  },
  {
    id: '2',
    category: 'service',
    title: 'HVAC Installation',
    content: 'Full installation of central air, heat pumps, and furnaces. Free site visit and quote. Financing available on installs over $3,000.',
  },
  {
    id: '3',
    category: 'pricing',
    title: 'Call-out Fee',
    content: 'Standard call-out: $89. Emergency call-out: $120. Both credited toward completed work.',
  },
  {
    id: '4',
    category: 'pricing',
    title: 'Annual Maintenance Plan',
    content: '$249/year per system. Includes 2 tune-ups, priority booking, 15% off repairs, no overtime fees.',
  },
  {
    id: '5',
    category: 'faq',
    title: 'Do you offer same-day service?',
    content: 'Yes, for emergencies in our primary service area. Book before 2 PM for same-day arrival.',
  },
  {
    id: '6',
    category: 'faq',
    title: 'What areas do you cover?',
    content: 'Primary area: within 20 miles of our shop. Extended area: 20-40 miles with a small travel fee.',
  },
  {
    id: '7',
    category: 'policy',
    title: 'Cancellation Policy',
    content: 'No charge for cancellations made 24+ hours in advance. Same-day cancellations may incur a $35 fee.',
  },
  {
    id: '8',
    category: 'hours',
    title: 'Business Hours',
    content: 'Mon-Fri 7am-7pm, Sat 8am-5pm, Sun closed. Emergency line available 24/7.',
  },
  {
    id: '9',
    category: 'offer',
    title: 'Senior Discount',
    content: '10% off all services for customers 65+. Mention when booking.',
  },
];

export const demoEmployees: AIEmployee[] = [
  {
    id: 'receptionist',
    name: 'AI Receptionist',
    role: 'Answers calls & chats 24/7',
    description: 'Never misses a customer. Answers questions, captures leads, and books appointments — even after hours.',
    status: 'active',
    icon: 'headset',
    conversations: 47,
    actions: 23,
  },
  {
    id: 'sales',
    name: 'AI Sales Assistant',
    role: 'Qualifies & follows up with leads',
    description: 'Follows up with every lead, answers pricing questions, and moves ready customers toward booking.',
    status: 'active',
    icon: 'handshake',
    conversations: 18,
    actions: 9,
  },
  {
    id: 'appointments',
    name: 'AI Appointment Assistant',
    role: 'Schedules & confirms bookings',
    description: 'Offers available slots, sends confirmations and reminders, and handles reschedule requests.',
    status: 'active',
    icon: 'calendar',
    conversations: 12,
    actions: 8,
  },
  {
    id: 'marketing',
    name: 'AI Marketing Assistant',
    role: 'Drafts campaigns for your approval',
    description: 'Suggests seasonal campaigns and follow-up messages. Nothing sends without your approval.',
    status: 'setup',
    icon: 'megaphone',
    conversations: 0,
    actions: 0,
  },
  {
    id: 'reviews',
    name: 'AI Review Manager',
    role: 'Requests & responds to reviews',
    description: 'Asks happy customers for reviews and drafts responses to feedback for your approval.',
    status: 'setup',
    icon: 'star',
    conversations: 0,
    actions: 0,
  },
];

export const plans: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    tagline: 'Try the AI Receptionist on your site',
    features: [
      'AI Receptionist on your website',
      'Up to 50 conversations / month',
      'Lead capture & basic dashboard',
      '1 AI employee active',
    ],
    cta: 'Start Free',
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 49,
    tagline: 'For solo owners getting started',
    features: [
      'Everything in Free',
      'Up to 500 conversations / month',
      'Lead & appointment management',
      '3 AI employees active',
      'Email support',
    ],
    cta: 'Start Starter',
  },
  {
    id: 'growth',
    name: 'Growth',
    price: 149,
    tagline: 'For growing teams with more demand',
    features: [
      'Everything in Starter',
      'Up to 2,000 conversations / month',
      'All 5 AI employees active',
      'Knowledge base & custom FAQs',
      'Review & marketing assistants',
      'Priority support',
    ],
    highlight: true,
    cta: 'Start Growth',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 399,
    tagline: 'For multi-location operations',
    features: [
      'Everything in Growth',
      'Unlimited conversations',
      'Multi-location support',
      'Custom AI training',
      'API & integrations',
      'Dedicated success manager',
    ],
    cta: 'Talk to Sales',
  },
];
